Repository akashchouhan16/Data-Structures-And-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#109 init TimeMap - time based store class
  Design-&-Implementations/TimeBasedKeyValueStore.cpp
Labels: hacktoberfest-accepted

#110 Init Sample Output case for PR #109
  Design-&-Implementations/TimeBasedKeyValueStore.cpp
Labels: hacktoberfest-accepted

#112 LC-732 : Design Calendar III
  Design-&-Implementations/Calendar_III.cpp
Labels: hacktoberfest-accepted

#114 LC-731 : Design Calendar II for Issue #113
  Design-&-Implementations/Calendar_II.cpp
Labels: hacktoberfest-accepted

#125 Shortest Palindrome Problem - Strings
  Strings/Shortest_Palindrome.cpp
Labels: string based

#124 Remove K digits Problem - Stack
  Stack/removeKdigits.cpp
Labels: stacks & queues, hacktoberfest-accepted

#127 Longest Happy Prefix Problem - Strings
  Strings/longestHappyPrefix.cpp
Labels: hacktoberfest-accepted, string based
